services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/bookingdb
    volumes:
      - ./data:/app/data
    networks:
      booking-net:
        aliases:
          - booking-backend

  frontend:
    build: ./booking-frontend
    ports:
      - "4200:4200"
    depends_on:
      - app
    networks:
      - booking-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --http-port 8180
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8180:8180"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      booking-net:
        aliases:
          - auth-server

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      - booking-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - booking-net

networks:
  booking-net:
    driver: bridge

volumes:
  keycloak_data:
