spring.application.name=demo

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/bookingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Keycloak / OAuth2 Configuration (PRO Setup)
# Usamos 'auth-server' como host unificado
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://auth-server:8180/realms/booking-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-server:8180/realms/booking-realm/protocol/openid-connect/certs

# Observability / Actuator
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
